version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
    environment:
      HTTPS_METHOD: nohttps
      HSTS: 'off'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vhost:/etc/nginx/vhost.d:ro
    networks:
      - proxy-tier
    restart: unless-stopped

networks:
  proxy-tier:
    external:
      name: nginx-proxy
