version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
    environment:
      HTTPS_MTEHOD: nohttps
      HSTS: 'off'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy
