version: '2.4'

services:
  updater:
    image: ghcr.io/linuxserver/duckdns
    environment:
      SUBDOMAINS: ${DUCKDNS_SUBDOMAINS}
      TOKEN: ${DUCKDNS_TOKEN}
      TZ: America/Los_Angeles
      LOG_FILE: "false"
    restart: unless-stopped
