version: '2'

services:
  dns:
    image: mvance/unbound-rpi:latest
    volumes:
      - ./a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro
    networks:
      internal:
        ipv4_address: 10.2.0.2
    restart: unless-stopped

  ad_blocker:
    image: pihole/pihole:latest
    depends_on:
      - dns
    ports:
      - 53:53/tcp
      - 53:53/udp
    expose:
      - 80
    dns:
      - 127.0.0.1
      - 10.2.0.2
    environment:
      TZ: America/Los_Angeles
      WEBPASSWORD: ""
      TEMPERATUREUNIT: f
      PIHOLE_DNS_: 10.2.0.2;10.2.0.2
      VIRTUAL_HOST: pihole.bb
    volumes:
      - data:/etc/pihole/
      - dnsmasq:/etc/dnsmasq.d/
    restart: unless-stopped
    networks:
      internal:
      proxy-tier:

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/29
  proxy-tier:
    external:
      name: nginx-proxy

volumes:
  data:
    driver: local
  dnsmasq:
    driver: local
