version: '2.4'

services:
  backup:
    image: awlnx/samba-timemachine
    ports:
      - 10445:445
    environment:
      USER: ${TIMEMACHINE_USER}
      PASS: ${TIMEMACHINE_PASSWORD}
      SHARENAME: ${TIMEMACHINE_SHARENAME}
      TMSIZE: ${TIMEMACHINE_SIZE}
    volumes:
      - data:/backups
    restart: unless-stopped

volumes:
  data:
