version: '2'

services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      - wiki:/wiki
    expose:
      - 4567
    environment:
      VIRTUAL_HOST: wiki.bb
    networks:
      - proxy-tier


volumes:
  wiki:
    driver: local

networks:
  proxy-tier:
    external:
      name: nginx-proxy
