version: '2'

services:
  vpn:
    image: linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      TZ: America/Los_Angeles
      SERVERURL:
      SERVERPORT: 51820
      PEERS:
      PEERDNS: auto
      INTERNAL_SUBNET: 10.13.13.0
      ALLOWEDIPS: 10.13.13.0/24,${LAN_CIDR}
    volumes:
      - config:/config
    ports:
      - '51820:51820/udp'
    restart: unless-stopped

volumes:
  config:
    driver: local
